config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :model_lists
  devise_for :users
  resources :categories
  root "model_lists#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :role
	belongs_to :model_list
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_permission, only: [:show, :edit, :update, :destroy]

  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.require(:permission).permit(:model_list_id, :is_create, :is_read, :is_update, :is_destroy, :role_id)
    end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<div class="container">
<div class="row">
<div class=-"col-md-8">
<div class="form-group">
<%= form_with(model: permission, local: true) do |form| %>
  <% if permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="dropdown">
    <%= form.label :model_list_id %>
    <%= form.collection_select :model_list_id, ModelList.all, :id, :name, prompt: "Select Model",  class: "dropdown-menu" %><br /><br />
  </div>
 
  <div class="field">
    <%= form.label :is_create %>
   <%= form.radio_button :is_create, 'true', :checked => true %>
   
   <%= form.radio_button :is_create, 'false', :checked => false %><br />
  </div>

  <div class="field">
    <%= form.label :is_read %>
    <%= form.radio_button :is_read, 'true', :checked => true %>
   
   <%= form.radio_button :is_read, 'false', :checked => false %>
  </div>

  <div class="field">
    <%= form.label :is_update %>
    <%= form.radio_button :is_update, 'true', :checked => true %>
   
   <%= form.radio_button :is_update, 'false', :checked => false %>
  </div>


  <div class="field">
  <%= form.label :is_destroy %>
  <%= form.radio_button :is_destroy, 'true', :checked => true %>
   
   <%= form.radio_button :is_destroy, 'false', :checked => false %>

  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.collection_select :role_id, Role.all, :id, :name, prompt: "Select Role" %><br /><br />
  </div>

  <div class="actions">
 <% if params[:id].nil? %>
 <%= form.submit "Add permission",  class: "btn btn-primary" %>
     <% else %>
     <%= form.submit "Update permission", class: "btn btn-primary" %>
     <% end %>
 </div>
<% end %>

</div>
</div>
</div>

app/views/permissions/edit.html.erb
<h1>Editing Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permissions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Model list</th>
      <th>Is create</th>
      <th>Is read</th>
      <th>Is update</th>
      <th> Is destroy</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%= permission.model_list_id %></td>
        <td><%= permission.is_create %></td>
        <td><%= permission.is_read %></td>
        <td><%= permission.is_update %></td>
        <td><%= permission.is_destroy %></td>
        <td><%= permission.role_id %></td>
        <td><%= link_to 'Show', permission %></td>
        <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
        <td><%= link_to 'Destroy', permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permission', new_permission_path %>

app/views/permissions/new.html.erb
<h1>New Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model list:</strong>
  <%= @permission.model_list_id %>
</p>

<p>
  <strong>Is create:</strong>
  <%= @permission.is_create %>
</p>

<p>
  <strong>Is read:</strong>
  <%= @permission.is_read %>
</p>

<p>
  <strong>Is update:</strong>
  <%= @permission.is_update %>
</p>


<p>
  <strong>Is destroy:</strong>
  <%= @permission.is_destroy%>
</p>

<p>
  <strong>Role:</strong>
  <%= @permission.role_id %>
</p>

<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>