config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :model_lists
  devise_for :users
  resources :categories
  root "model_lists#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/model_list.rb
class ModelList < ApplicationRecord
	has_many :permissions
end

app/controllers/model_lists_controller.rb
class ModelListsController < ApplicationController
  before_action :set_model_list, only: [:show, :edit, :update, :destroy]
load_and_authorize_resource
  # GET /model_lists
  # GET /model_lists.json
  def index
    @model_lists = ModelList.all
  end

  # GET /model_lists/1
  # GET /model_lists/1.json
  def show
  end

  # GET /model_lists/new
  def new
    @model_list = ModelList.new
  end

  # GET /model_lists/1/edit
  def edit
  end

  # POST /model_lists
  # POST /model_lists.json
  def create
    @model_list = ModelList.new(model_list_params)

    respond_to do |format|
      if @model_list.save
        format.html { redirect_to @model_list, notice: 'Model list was successfully created.' }
        format.json { render :show, status: :created, location: @model_list }
      else
        format.html { render :new }
        format.json { render json: @model_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_lists/1
  # PATCH/PUT /model_lists/1.json
  def update
    respond_to do |format|
      if @model_list.update(model_list_params)
        format.html { redirect_to @model_list, notice: 'Model list was successfully updated.' }
        format.json { render :show, status: :ok, location: @model_list }
      else
        format.html { render :edit }
        format.json { render json: @model_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_lists/1
  # DELETE /model_lists/1.json
  def destroy
    @model_list.destroy
    respond_to do |format|
      format.html { redirect_to model_lists_url, notice: 'Model list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model_list
      @model_list = ModelList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_list_params
      params.require(:model_list).permit(:name)
    end
end

app/helpers/model_lists_helper.rb
module ModelListsHelper
end

app/views/model_lists/_form.html.erb
<%= form_with(model: model_list, local: true) do |form| %>
  <% if model_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model_list.errors.count, "error") %> prohibited this model_list from being saved:</h2>

      <ul>
      <% model_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :model_list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/model_lists/edit.html.erb
<h1>Editing Model List</h1>

<%= render 'form', model_list: @model_list %>

<%= link_to 'Show', @model_list %> |
<%= link_to 'Back', model_lists_path %>

app/views/model_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Model Lists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @model_lists.each do |model_list| %>
      <tr>
        <td><%= model_list.name %></td>
        <td><%= link_to 'Show', model_list %></td>
        <td><%= link_to 'Edit', edit_model_list_path(model_list) %></td>
        <td><%= link_to 'Destroy', model_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model List', new_model_list_path %>

app/views/model_lists/new.html.erb
<h1>New Model List</h1>

<%= render 'form', model_list: @model_list %>

<%= link_to 'Back', model_lists_path %>

app/views/model_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @model_list.name %>
</p>

<%= link_to 'Edit', edit_model_list_path(@model_list) %> |
<%= link_to 'Back', model_lists_path %>